version: '3.8'

services:
  translation-pwa:
    build: .
    container_name: translation-pwa
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./backend/uploads:/app/backend/uploads
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - SMTP_SERVER=${SMTP_SERVER:-localhost}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@ballerup.dk}
      - CUDA_VISIBLE_DEVICES=0
      - COQUI_TTS_LICENSE_ACCEPTED=true
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - PYTORCH_NVML_BASED_CUDA_CHECK=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:512
      - CUDA_LAUNCH_BLOCKING=0
      - BNB_CUDA_VERSION=""
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/translation-pwa/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]